### ISSUE TITLE
File name has embedded space

### ISSUE THREAD

**Issue by ansco11** [gobo-eiffel/gobo#33]
library/tools/test/eiffel/validity/vevi/test23 has "failed1 .gelint" where it should be "failed1.gelint"

**Comment by ebezault** [comment]
Thank you for pointing that out to me. It's now fixed in the Git repository.
Note that there are old tests in library/tools/test/eiffel which have not been looked at for a long time. Some of them may not even compile, or may not reflect the current state of the Eiffel language.
I'm planning to address this issue in the next release of Gobo.
